# @package _global_

defaults:
  - social_rearrange: pop_play
  - hitl_defaults
  - _self_

habitat:
  environment:
    max_episode_steps: 0
  task:
    measurements:
      rearrange_cooperate_reward:
        end_on_collide: False
      pddl_success:
        must_call_stop: False

habitat_baselines:
  evaluate: True
  num_environments: 1

habitat_hitl:
  gui_controlled_agent_index: 1

pick_throw_vr:
