# @package _global_

defaults:
  - social_rearrange: pop_play
  - hitl_defaults
  - _self_

habitat:
  environment:
    max_episode_steps: 0
    iterator_options:
      cycle: False
  task:
    measurements:
      pddl_success:
        must_call_stop: False

habitat_baselines:
  evaluate: True
  num_environments: 1
  eval:
    should_load_ckpt: False
  rl:
    agent:
      num_pool_agents_per_type: [1,1]

habitat_hitl:
  gui_controlled_agent_index: 1

rearrange:
  # Shows an intro sequence before the first episode that helps familiarize the user to task in a HITL context.
  show_tutorial: True
