habitat_hitl:

  window:
    # Horizontal resolution of the window.
    width: 1280
    # Vertical resolution of the window.
    height: 720

  # Target rate to step the environment (steps per second); actual SPS may be lower depending on your hardware
  target_sps: 30

  # Episodes filter in the form '0:10 12 14:20:2', where single integer number (`12` in this case) represents an episode id, colon separated integers (`0:10' and `14:20:2`) represent start:stop:step ids range.
  episodes_filter: ~

  experimental:
    # Choose between classic and batch renderer.
    use_batch_renderer: False

  debug_third_person_viewport:
    # If specified, enable the debug third-person camera (habitat.simulator.debug_render) with specified viewport width. If height (below) is not specified, assume square aspect ratio (height==width).
    width: ~
    # If specified, use the specified viewport height for the debug third-person camera.
    height: ~

  # Visualize camera sensors in the app GUI. For example, to visualize agent1's head depth sensor, include "agent_1_head_depth" in this list.
  debug_images: []

  # The speed of the default animation timer. See sandbox_service.get_anim_fraction. Currently used to animate some debug lines.
  viz_animation_speed: 2.0

  # Hide the humanoid in the GUI viewport. Note it will still be rendered into observations fed to policies. Mainly used for camera first-person mode (below).
  hide_humanoid_in_gui: False

  # Object grasp/place proximity threshold. See GuiPickHelper.
  can_grasp_place_threshold: 1.2

  # See GuiHumanoidController.
  walk_pose_path: "data/humanoids/humanoid_data/walking_motion_processed_smplx.pkl"

  # When enabled, a HITL app behaves as a server that takes input from a remote client.
  # See pick_throw_vr example app.
  remote_gui_mode: False

  camera:
    # See CameraHelper. Choose between first-person and third-person camera.
    # When using first-person mode, you should also:
    #   * set hide_humanoid_in_gui=True to avoid visual artifacts, and
    #   * set gui_controlled_agent.ang_speed=300 to avoid delayed movement after turning
    first_person_mode: False
    # Look up angle limit. See CameraHelper.
    max_look_up_angle: 15.0
    # Look down angle limit.
    min_look_down_angle: -60.0

  gui_controlled_agent:
    # GUI-controlled agent index (must be None or >= 0 and < number of agents).
    # Defaults to None, indicating that all the agents are policy-controlled.
    agent_index: ~
    # linear speed
    lin_speed: 10.0
    # angular speed
    ang_speed: 10.0

  data_collection:
    # Filepath base used for saving various session data files. Include a full path including basename, but not an extension.
    save_filepath_base: None
    # Save the gfx-replay keyframes to file. Use filepath_base to specify the filepath base.
    save_gfx_replay_keyframes: False
    # Save recorded episode data to file. Use filepath_base to specify the filepath base.
    save_episode_record: False
